{% set name = "moe" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/moe-{{ version }}.tar.gz
  sha256: 3c98f5fbca3d996b779e3c5d15391c621f4f17138f3dfebf419bb16d14cf0fe2

build:
  entry_points:
    - moe = moe.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0
    - pip
  run:
    - python >={{ python_min }}
    - alembic >=1.4.2,<2.0.0
    - dynaconf >=3.1.4,<4.0.0
    - mediafile >=0.13.0,<0.14.0
    - musicbrainzngs >=0.7.1,<0.8.0
    - pluggy >=1.3.0,<2.0.0
    - rich >=13.0.0,<14.0.0
    - sqlalchemy >=2.0.0,<3.0.0
    - unidecode >=1.2.0,<2.0.0
    - questionary >=2.0.0,<3.0.0
    - importlib-metadata >=7.0.1,<8.0.0

test:
  imports:
    - moe
  commands:
    - pip check
    - moe --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MoeMusic/Moe
  summary: The ultimate tool for managing your music library.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/MoeMusic/Moe
  doc_url: https://mrmoe.readthedocs.io/

extra:
  recipe-maintainers:
    - HeavyTony2
