schema_version: 1

context:
  name: moe
  version: 2.5.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/moe-${{ version }}.tar.gz
  sha256: db57c4f6fd5bf74c9059fdcbeeddbef9e6528de65176910899360027b0551553

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - moe = moe.cli:main

requirements:
  host:
    - python ${{ python_min }}*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - alembic >=1.4.2,<2.0.0
    - dynaconf >=3.1.4,<4.0.0
    - mediafile >=0.13.0,<0.14.0
    - musicbrainzngs >=0.7.1,<0.8.0
    - pluggy >=1.3.0,<2.0.0
    - rich >=13.0.0,<14.0.0
    - sqlalchemy >=2.0.0,<3.0.0
    - unidecode >=1.2.0,<2.0.0
    - questionary >=2.0.0,<3.0.0
    - importlib-metadata >=7.0.1,<8.0.0

tests:
  - python:
      imports:
        - moe
  - requirements:
      run:
        - pip
        - python ${{ python_min }}*
    script:
      - pip check
      - moe --help

about:
  summary: The ultimate tool for managing your music library.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/MoeMusic/Moe
  repository: https://github.com/MoeMusic/Moe
  documentation: https://mrmoe.readthedocs.io/

extra:
  recipe-maintainers:
    - HeavyTony2
